---
title: "Calendars"
---

Here are some fun calendars with important dates highlighted! 

```{r,echo=FALSE, message=FALSE, warning=FALSE, results=FALSE}
library(calendR)
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}

### MARCH 2022 ##########
# Vector of dates
dates <- seq(as.Date("2022-03-01"), as.Date("2022-03-31"), by = "1 day")

events <- rep(NA, 31)
events[c(11, 12, 13, 14, 15)] <- "Example 1"
events[24] <- "Example 2"
events[28] <- "Example 3"


# Creating the calendar
calendR(year = 2022, month = 3,
        start = "M",
        special.days = events,
        special.col = c("lightblue", "pink",  # As many colors
                        "mediumpurple2"), # as events
        low.col = "white",
        legend.pos = "bottom", # Legend position
        legend.title = "",
        title = "March 2022") 

```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
### APRIL 2022 ##########
# Vector of dates
dates <- seq(as.Date("2022-04-01"), as.Date("2022-04-30"), by = "1 day")

events2 <- rep(NA, 30)
events2[9] <- "Example 1"
events2[11] <- "Example 2"
events2[20] <- "Example 3"
events2[28] <- "Example 4"


# Creating the calendar
calendR(year = 2022, month = 4,
        start = "M",
        special.days = events2,
        special.col = c("lightblue", "pink",  # As many colors
                        "mediumpurple2", "orangered"), # as events
        low.col = "white",
        legend.pos = "bottom", # Legend position
        legend.title = "",
        title = "April 2022")   
```




